import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Dexter</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link
                    rel='icon'
                    href='/favicon.ico'
                />
                <link
                    rel='icon'
                    href='/logo.png'
                />
            </Head>
            <main className='m-0'>
                <h1>Dexter</h1>
                <p>Lorem ipsum dolor amet</p>
                <Link href='pokemons/'>POKEMONS</Link>
            </main>
        </>
    );
};

export default Home;
