import { Pokemons } from '@/components';
import { getPokemons } from '@/services/pokemons-services';
import { type SimplePokemon } from '@/types/pokemon-types';
import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';

interface Props {
    pokemons: SimplePokemon[];
    page: number;
}

const Home: NextPage<Props> = ({ pokemons, page }: Props) => {
    return (
        <>
            <Head>
                <title>Dexter</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
            </Head>
            <main className='m-0'>
                <Pokemons
                    pokemons={pokemons}
                    page={page}
                />
            </main>
        </>
    );
};

export const getServerSideProps: GetServerSideProps = async context => {
    const { page } = context.query;

    const pokemons: SimplePokemon[] = await getPokemons({
        perPage: 10,
        page: page ? parseInt(page as string) : 1,
    });

    return {
        props: {
            pokemons,
            page: page ?? 1,
        },
    };
};

export default Home;
