import Pokemons from '@/components/pokemons/pokemons';
import { getPokemons } from '@/services/pokemons-services';
import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import type { Pokemon } from 'pokenode-ts';

interface Props {
    pokemons: Pokemon[];
}

const Home: NextPage<Props> = ({ pokemons }: Props) => {
    return (
        <>
            <Head>
                <title>Dexter</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
            </Head>
            <main className='m-0'>
                <Pokemons pokemons={pokemons} />
            </main>
        </>
    );
};

export const getServerSideProps: GetServerSideProps = async context => {
    const pokemons: Pokemon[] = await getPokemons({ perPage: 10, offset: 200 });

    return {
        props: {
            pokemons,
        },
    };
};

export default Home;
