export const pokemonBackgrounds = {
    normal: 'normalBackground',
    fire: 'fireBackground',
    water: 'waterBackground',
    electric: 'electricBackground',
    ground: 'groundBackground',
    grass: 'grassBackground',
    ice: 'iceBackground',
    poison: 'poisonBackground',
    flying: 'flyingBackground',
    psychic: 'psychicBackground',
    bug: 'bugBackground',
    rock: 'rockBackground',
    fighting: 'fightingBackground',
    ghost: 'ghostBackground',
    dragon: 'dragonBackground',
    dark: 'darkBackground',
    steel: 'steelBackground',
    fairy: 'fairyBackground',
};
